### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ripemd** [i-net-software/dokuwiki-plugin-imagemap#12]
Hello,
I'm using your plugin quite a lot within my dokuwiki. As an improvement I would like to ask if there is a chance to add the possibility to link directly to a file? 

Example:
[[example.pdf|Description @ 10,12,40,30]]

Thanks a lot!
ripe_md

**Comment by gamma** [comment]
Shouldn't be too hard. I'll check for it.

**Comment by ripemd** [comment]
Thank's a lot for following up!

**Comment by ripemd** [comment]
I don't want to sound too pushy, but did you have a chance to verify if it can be implemented?

Your feedback is highly appreciated
ripe_md

**Comment by ripemd** [comment]
I found a solution to support the following syntax:
{{example.pdf|Description @ 10,12,40,30}}

Within syntax.php the following needs to be amended:

```php
function render($format, Doku_Renderer $renderer, $data) {
    ...
    case DOKU_LEXER_MATCHED:
        if ($data[1]=='area') {
            ...
            switch ($type) {
		...
		case 'internalmedia':
		        list($url,$hash) = explode('#',$url,2);
			resolve_mediaid(getNS($ID), $url, $exists);
			$title = $renderer->_media($url, $title, null,null,null,null, false);
			$url = ml($url, ($extra[1]=='direct'));
			if ($hash) $url .= '#'.$hash;
			break;
	}
```

I haven't updated the code to support DokuWiki versions before Destritus. My installed version is "Elenor of Tsort"

**Comment by gamma** [comment]
Can you create a pull request please?
