### ISSUE TITLE
Fatal error: Call to a member function writeCall() on null

### ISSUE THREAD

**Issue by LukasHirsch** [i-net-software/dokuwiki-plugin-imagemap#16]
Hi,
after installing **Release rc2020-06-01 "Hogfather"** today i get the following error: 
`Fatal error: Call to a member function writeCall() on null in C:\...\dokuwiki\lib\plugins\imagemapping\syntax.php on line 272`

Then I cannot access the wiki any more and need to rename the plugin folder (e.g. \dokuwiki\lib\plugins\old_imagemapping) or delete the `{{map> }}` section from the page via the explorer.

Any ideas on how to fix this?

**Comment by tmo26** [comment]
Which version of the plugin do you have installed?

**Comment by LukasHirsch** [comment]
It's the latest version from this repo, should be 2017-08-19?
I also tried deleting and reinstalling it, so the latest version available over the extension manager.

I had a Wiki running Greebo_2018-04-22b where it worked. With the last release of Greebo_2018-04-22c it stopped working, but did not show any errors. Just the actual mapping of pictures isn't working anymore, but the pictures are there.

In a second wiki I upgraded vom Grebe_2018-04-22b to Hogfather_2020-06-01 (release 1) and got the fatal error.

Hope this helps to find a solution? 
Thanks!

**Comment by gamma** [comment]
I do not yet have the time to check and fix. Any help is appreciated.

**Comment by tmo26** [comment]
Does the issue persist with the latest version of Dokuwiki (Hogfather RC3) the plugin (version 2020-06-16)?
I have Hogfather RC3 working perfectly with this plugin version.

**Comment by LukasHirsch** [comment]
Fantastic, it works again! Thank you very much!

- DokuWiki Hogfather RC3 2020-06-09
- Image Map Plugin (by Gerry Weißbach) 2020-06-16
