### ISSUE TITLE
Responsive imagemap

### ISSUE THREAD

**Issue by TomR** [i-net-software/dokuwiki-plugin-imagemap#8]
What is the correct syntax to show an image which will be responsive ( including scaling of coordinates )?
I was not able to figure that out.

Would welcome any help.

**Comment by gamma** [comment]
Hey Tom, there is no such functionality as of now.

**Comment by TomR** [comment]
Thanks for your swift reply.

The comment in `jquery.rwdImageMaps.js`suggested otherwise to me ;-)

```
*
* rwdImageMaps jQuery plugin v1.5
*
* Allows image maps to be used in a responsive design by recalculating the area coordinates to match the actual image size on load and window.resize
*
* Copyright (c) 2013 Matt Stow
* https://github.com/stowball/jQuery-rwdImageMaps
* http://mattstow.com
* Licensed under the MIT license
*/
```

**Comment by gamma** [comment]
To be honest: I did not write that part of the code, it was contributed to this plugin. If it provides such functionality it should work right out of the box without any syntax changes. I only had a quick look at this portion of the code ... could you debug this part and check the outcome? (sorry but this is not on my list for some time ;))

**Comment by TomR** [comment]
I will take a look at it. However that is not my expertise. So could not promise anything ;-)
However thanks for your replies.
